### PR TITLE
Include Buyer, Seller, & Service

### PR DESCRIPTION
**Pull request by 7H3LaughingMan**
These will be available in the macro using `scope.buyer`, `scope.seller`, `scope.service`

### CODE REVIEW

**Comment by reonZ** [comment]
Why though ? What can you do with the service itself or the price ?

**Comment by 7H3LaughingMan** [comment]
> Why though ? What can you do with the service itself or the price ?

This is so you can re-use macros. For example, let's say you have a service to cast Heal on a player. The macro can do more healing based on the level of the service. Another example is for stuff like lodging, so you can have one macro for different services. The price though might not matter as much, but it's just one extra bit of information.

**Comment by reonZ** [comment]
Yeah, the level make sense, but other than that, services have no identifying features in them.

**Comment by 7H3LaughingMan** [comment]
> Yeah, the level make sense, but other than that, services have no identifying features in them.

My lodging macro includes the name of the seller and the name of the service in the Simple Calendar note that is created. This way I can know what inn/hotel/tavern/etc. they are staying at and if they get anything special. You never know what someone can use the name for at least. I also use the quantity so that players can purchase multiple days of stays in one go.

**Comment by reonZ** [comment]
I implemented something similar in `2.15.0`, you  can see the details of the parameters [here](https://github.com/reonZ/pf2e-toolbelt/wiki/Better-Merchant#service-macro)

**Comment by reonZ** [comment]
I implemented something similar in `2.15.0`, you  can see the details of the parameters [here](https://github.com/reonZ/pf2e-toolbelt/wiki/Better-Merchant#service-macro)

**Pull request closed without merging**
